### ISSUE TITLE
How did this work out for the class?

### ISSUE THREAD

**Issue by addisonj** [chesles/node-arff#2]
Apologies for the non-issue issue. It was the best way to get a hold of you :)

I am in BYU CS478 this semester and wondered how things worked out doing the class in node. Where you able to complete all the projects in node or did you run into any large problems?

Thanks for the this project and appreciate any help!

**Comment by toddpi314** [comment]
FYI, v1 of this component works just fine for large scale ARFF parsing.
We are running it through billions of ARFF files and the only major issue found was addressed in PR https://github.com/chesles/node-arff/pull/4

In terms of algorithm design, this isn't 1990 and this isn't a C++ component. Just run the code through google-closure/uglifyJS as part of your NPM build and you will achieve the almost-perfect runtimes. Also realize that most browsers will optimize your code at compile time anyways. These days, it is better to make code readable/communicable than ASM-style runtime perfect.

Good work.

**Comment by chesles** [comment]
Great to hear this has been useful @toddpi314! I originally created it for a class in university- I never would have imagined that it would ever be used on billions of files! I'm glad it's working well for you.
